# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on: [push, pull_request]

jobs:
  ci:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 10
    - name: Use Node.js 12.x to build
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm run build
    - run: rm -rf node_modules
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run test
      env:
        CI: true
    - run: npm run lint
      if: matrix.node-version == '12.x'
    - run: npm run docs:diff
      if: matrix.node-version == '12.x'
    - run: npm run bundlewatch
      if: matrix.node-version == '12.x'
      env:
        CI: true
